name: FINAL_EXAM_GIT_ACTIONS

env:
  GLOBAL_FIRST_NAME: "Atef"

on:
  push:
    branches:
      - main
     
jobs:

  job1:
    runs-on: ubuntu-latest
    steps:
   
    - name: Print Hello message
      run: echo "Hello"
     
    - name: Print Ubuntu version
      run: cat /etc/lsb-release | grep "DISTRIB_DESCRIPTION"
     
    - name: Print Last SHA Key
      run: echo "Last Commit ( SHA ) is ${{ github.sha }}"
 
  job2:
    runs-on: ubuntu-latest
    steps:
   
    - uses: actions/checkout@v3
   
    - name: Print GIT content
      run: ls -la
     
    - name: Print all files
      run: for file_name in $(ls *.txt); do echo "File name is $file_name"; echo "File content is"; echo "$(cat $file_name)"; echo "" ; done
     
    - name: Run test.sh BASH Script
      run: bash test.sh
   
  job3:
    runs-on: ubuntu-latest
    steps:
   
      - name: Print First Name using environment variables
        run: echo "My First Name ( from environment ) is ${{ env.GLOBAL_FIRST_NAME }}"
     
      - name: Print Last Name using local variables
        run: echo "My Last Name ( from local ) is $LOCAL_LAST_NAME "
        env:
          LOCAL_LAST_NAME: "Shehadeh"
      
      - name: Print phone number using secrets variables
        run: echo "My Phone number ( from secrets ) is ${{ secrets.SEC_PHONE }}"
